namespace: go-app-static
replicaCount: 2
appLabel: go-app-demo
containerName: go-app-container
containerPort: 8080

image:
  repository: ghcr.io/gesatessa/devops_eks
  tag: "main-66c27ca8197e76ec56d6880d19f273fa56f538fc"
  pullPolicy: Always

imagePullSecret: ghcr-secret

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "128Mi"

service:
  type: ClusterIP  # or NodePort
  nodePort: 30080  # only used when type is NodePort
